### ISSUE TITLE
Running Notebooks Using Docker

### ISSUE THREAD

**Issue by psychemedia** [nicolewhite/neo4j-jupyter#1]
To try to get quickstarted on this, I used a docker compose file to wire together a scipy notebook and neo4j using the following `docker-compose.yml` file:

```
neo4j:
  image: kbastani/docker-neo4j:latest
  ports:
    - "7474:7474"
    - "1337:1337"
  volumes:
    - /opt/data
jupyterscipy:
  image: jupyter/scipy-notebook
  ports:
    - "8888:8888"
  links:
    - neo4j:neo4j
```

 `cd` into the directory containing the `docker-compose.yml` file and run: `docker-compose up -d`

To connect to the neo4j db: `graph = Graph("http://neo4j:7474/db/data/")`

Also, I note that when running the `hello-world` notebook, you try to save an image into the `figure` dir, which may not exist. Something like `mkdir -p figure` should fix that?
